
@subdominio=idat-render-knhd


GET https://{{subdominio}}.onrender.com/idynom

###
GET  https://{{subdominio}}.onrender.com/codigo
###

GET https://{{subdominio}}.onrender.com/nomcompl

######CON BASE DE DATOS #####

###
POST https://{{subdominio}}.onrender.com/demo/add
Content-Type: application/x-www-form-urlencoded

name=Desarrollo sistemas
&creditos=5

###
DELETE https://{{subdominio}}.onrender.com/demo/del
Content-Type: application/x-www-form-urlencoded

id=2

###
GET https://{{subdominio}}.onrender.com/demo/all
