package com.example.restservice;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;

import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
//import org.springframework.web.bind.annotation.PathVariable;
// imports for use List, Map, String and Object
import java.util.List;
import java.util.Map;
import java.lang.String;
import java.lang.Object;

import org.springframework.jdbc.core.JdbcTemplate;
// import org.springframework.jdbc.core.RowMapper;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@Autowired
	private JdbcTemplate jdbcTemplate;

	@PostMapping(path = "/add") // Map ONLY POST Requests
	public @ResponseBody String addNewCurso(@RequestParam String name, @RequestParam String creditos) {
		cursos n = new cursos();
		n.setName(name);
		n.setCredito(creditos);
		userRepository.save(n);
		return "Saved";
	}

	@DeleteMapping(path = "/del")
	public @ResponseBody String delUser(@RequestParam Integer id) {
		cursos n = new cursos();
		n.setId(id);
		userRepository.delete(n);
		return "Deleted";
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<cursos> getAllCursos() {
		return userRepository.findAll();
	}

	@GetMapping(path = "/get/report")
	public @ResponseBody List getReport() {
		List<Map<String, Object>> queryResult = jdbcTemplate
				.queryForList("SELECT CONCAT(name, ' ==> ', credito) as mycol FROM user");
		return queryResult;
	}

}
